Feature/api
yrshyrsh/TaskManager pull request #13
Opened 2022-09-29 14:32 UTC by yrshyrsh

2022-09-29 16:09 UTC, greybutton requested changes

2022-09-29 16:09 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { create :developer }
почему поменял?

2022-09-30 11:04 UTC, yrshyrsh commented on test/factories/tasks.rb
> +    assignee_id { create :developer }
В задании сказано "Автором задачи может быть только пользователь с ролью manager. Исполнителем - только пользователь с ролью developer". Подумал так логичнее.

2022-09-30 17:59 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { create :developer }
но ведь так и было, я именно про изменения `association :author, factory: :manager` на `author_id { create :manager }` оже самое про assignee. и почему удалено expired_at

2022-10-01 12:04 UTC, yrshyrsh commented on test/factories/tasks.rb
> +    assignee_id { create :developer }
expired_at случайно потёр. ассоциации в тестах не до конца понял как работают, ещё на этапе создания валидаций, когда статические значения ( author_id { 1 } ) заменили, просто сделал как в задании написано. потом при тестировании по разному пробовал, и мне показалось понятнее генерировать id напрямую...   хотя сейчас смотрю, походу неправильно сделал, тут же именно id нужен... Вернуть как было ( с ассоциациями ) ?

2022-10-01 12:50 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { create :developer }
да и expired_at вернуть

2022-10-03 12:38 UTC, greybutton approved these changes

2022-10-03 15:42 UTC, merged